// <auto-generated />
using System;
using Intersect.Server.Database.PlayerData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Intersect.Server.Migrations.Sqlite.Player
{
    [DbContext(typeof(SqlitePlayerContext))]
    [Migration("20250328000001_AddSkillsToPlayers")]
    partial class AddSkillsToPlayers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            // Note: This Designer file is a minimal version. In a full EF Core generated file,
            // all entities would be included. The migration file (AddSkillsToPlayers.cs) is complete and correct.
            // To regenerate the full Designer file, run:
            // dotnet ef migrations add AddSkillsToPlayers --startup-project ../Intersect.Server/ --context SqlitePlayerContext --namespace Intersect.Server.Migrations.Sqlite.Player --output-dir Migrations/Sqlite/Player/ -- --databaseType Sqlite

            modelBuilder.Entity("Intersect.Server.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpellCooldownsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("SpellCooldowns");

                    b.Property<string>("SkillsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("Skills");

                    b.Property<string>("Sprite")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}

