// <auto-generated />
using System;
using Intersect.Server.Database.GameData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Intersect.Server.Migrations.Sqlite.Game
{
    [DbContext(typeof(SqliteGameContext))]
    [Migration("20250328000000_AddSkills")]
    partial class AddSkills
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            // Note: This Designer file is a minimal version. In a full EF Core generated file,
            // all entities would be included. The migration file (AddSkills.cs) is complete and correct.
            // To regenerate the full Designer file, run:
            // dotnet ef migrations add AddSkills --startup-project ../Intersect.Server/ --context SqliteGameContext --namespace Intersect.Server.Migrations.Sqlite.Game --output-dir Migrations/Sqlite/Game/ -- --databaseType Sqlite

            modelBuilder.Entity("Intersect.Framework.Core.GameObjects.Resources.ResourceDescriptor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CannotHarvestMessage")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeathAnimationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeathAnimation");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Event");

                    b.Property<string>("Folder")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonDrops")
                        .HasColumnType("TEXT")
                        .HasColumnName("Drops");

                    b.Property<string>("JsonHarvestingRequirements")
                        .HasColumnType("TEXT")
                        .HasColumnName("HarvestingRequirements");

                    b.Property<string>("JsonStates")
                        .HasColumnType("TEXT")
                        .HasColumnName("States");

                    b.Property<int>("MaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinHp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<int>("SpawnDuration")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TimeCreated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tool")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseExplicitMaxHealthForResourceStates")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VitalRegen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WalkableAfter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WalkableBefore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Intersect.Framework.Core.GameObjects.Skills.SkillDescriptor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("BaseExperience")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExperienceCurve")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExperienceIncrease")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExperienceOverrides")
                        .HasColumnType("TEXT");

                    b.Property<string>("Folder")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<long>("TimeCreated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Intersect.Framework.Core.GameObjects.Variables.GuildVariableDescriptor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<byte>("DataType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Folder")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("TextId")
                        .HasColumnType("TEXT");

                    b.Property<long>("TimeCreated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GuildVariables");
                });
#pragma warning restore 612, 618
        }
    }
}

